package rules

import (
	"fmt"
	"strings"
)

// LaneScope is the per-lane write scope that becomes an always-on Antigravity rule.
type LaneScope struct {
	AllowedPaths  []string
	ReadOnlyPaths []string
}

// LaneFiles renders the Antigravity rule files for one lane worktree, keyed by file name under
// .agents/rules/ (every file must carry a valid frontmatter `trigger`, or Antigravity silently
// drops it, and stay under 24 KB):
//
//   - lucind-worker.md: always_on, the `worker` and `all` sections of lucind-rules.md.
//   - lucind-lane-scope.md: always_on, this lane's allowed and read-only paths.
//   - lucind-result-envelope.md: model_decision (loaded on demand), the envelope contract with
//     the schema inlined through an @[label](path) include.
func LaneFiles(sections []Section, srcHash string, scope LaneScope) map[string][]byte {
	if len(srcHash) > 12 {
		srcHash = srcHash[:12]
	}
	marker := fmt.Sprintf("<!-- GENERATED by lucind-ai from lucind-rules.md (sha256:%s); do not edit -->\n\n", srcHash)

	var worker strings.Builder
	worker.WriteString(marker + "# Lane rules: worker\n\n")
	for _, s := range sections {
		if hasAudience(s.Audiences, "worker") || hasAudience(s.Audiences, "all") {
			worker.WriteString(strings.TrimSpace(s.Content) + "\n\n")
		}
	}

	var sc strings.Builder
	sc.WriteString(marker + "# Lane scope\n\n")
	if len(scope.AllowedPaths) == 0 {
		sc.WriteString("This is a read-only lane: do not create, edit or delete any file.\n\n")
	} else {
		sc.WriteString("You may create or modify only these paths (anything else is a deviation):\n\n")
		for _, p := range scope.AllowedPaths {
			sc.WriteString("- " + codeSpan(p) + "\n")
		}
		sc.WriteString("\n")
	}
	if len(scope.ReadOnlyPaths) > 0 {
		sc.WriteString("Declared inputs you may read but never write:\n\n")
		for _, p := range scope.ReadOnlyPaths {
			sc.WriteString("- " + codeSpan(p) + "\n")
		}
		sc.WriteString("\n")
	}

	envelope := marker + "# Result envelope\n\n" +
		"Write the result envelope to `.lucind/result.json` in this worktree. The required fields are `packet_id`, `status`, `summary` and `hard_stops`; the full contract is the schema below. " +
		"The dispatcher rejects an envelope that does not validate, and the Stop hook will send you back to fix it.\n\n" +
		"@[Result schema](../../.lucind/result.schema.json)\n"

	return map[string][]byte{
		"lucind-worker.md":     []byte(ruleFrontmatter("always_on", "Standing rules for lucind-ai lane workers.") + worker.String()),
		"lucind-lane-scope.md": []byte(ruleFrontmatter("always_on", "Which paths this lane may write.") + sc.String()),
		"lucind-result-envelope.md": []byte(ruleFrontmatter("model_decision",
			"Apply when writing, fixing or validating the lane result envelope .lucind/result.json.") + envelope),
	}
}

func ruleFrontmatter(trigger, description string) string {
	return fmt.Sprintf("---\ntrigger: %s\ndescription: %q\n---\n\n", trigger, description)
}

func hasAudience(audiences []string, want string) bool {
	for _, a := range audiences {
		if a == want {
			return true
		}
	}
	return false
}

// codeSpan renders a path as inline code that cannot break out of its line: control characters
// and backticks are replaced, so a hostile path cannot inject a heading or instructions.
func codeSpan(p string) string {
	clean := strings.Map(func(r rune) rune {
		if r < 0x20 || r == 0x7f || r == '`' {
			return '_'
		}
		return r
	}, p)
	return "`" + clean + "`"
}
