package rules

import (
	"bytes"
	"crypto/sha256"
	_ "embed"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

//go:embed default_rules.md
var defaultRules []byte

const (
	SourceName            = "lucind-rules.md"
	GeneratedMarkerPrefix = "<!-- GENERATED by lucind-ai rules generate"
)

type FileStatus string

const (
	StatusWritten            FileStatus = "written"
	StatusUnchanged          FileStatus = "unchanged"
	StatusStale              FileStatus = "stale"
	StatusMissing            FileStatus = "missing"
	StatusSkippedHandWritten FileStatus = "skipped_hand_written"
)

type TargetResult struct {
	File   string
	Status FileStatus
}

type Result struct {
	Targets []TargetResult
	Files   map[string]FileStatus
}

type Options struct {
	Check bool
}

type Section struct {
	Audiences []string
	Content   string
}

// Parse parses the markdown source according to lucind-ai rules syntax.
// A line of the exact form `<!-- lucind:rules audience=<list> -->` starts a section;
// <list> is a comma-separated, no-spaces subset of orchestrator, worker, all.
// The section body runs to the next marker or end of file.
// Text before the first marker, an unknown audience, an empty list, a duplicate
// audience within a marker, or a source with no section at all is an error with the line number.
func Parse(src []byte) ([]Section, error) {
	if len(src) == 0 {
		return nil, fmt.Errorf("line 1: source has no section markers")
	}

	contentStr := string(src)
	rawLines := strings.Split(contentStr, "\n")
	var lines []string
	for _, l := range rawLines {
		lines = append(lines, strings.TrimSuffix(l, "\r"))
	}

	const (
		markerPrefix = "<!-- lucind:rules audience="
		markerSuffix = " -->"
	)

	var sections []Section
	var currentSec *Section
	var currentBody strings.Builder

	for i, line := range lines {
		lineNum := i + 1

		if strings.HasPrefix(line, "<!-- lucind:rules") {
			if !strings.HasPrefix(line, markerPrefix) || !strings.HasSuffix(line, markerSuffix) {
				return nil, fmt.Errorf("line %d: invalid section marker format", lineNum)
			}
			audienceStr := line[len(markerPrefix) : len(line)-len(markerSuffix)]
			if audienceStr == "" {
				return nil, fmt.Errorf("line %d: empty audience list", lineNum)
			}
			if strings.Contains(audienceStr, " ") {
				return nil, fmt.Errorf("line %d: audience list must not contain spaces", lineNum)
			}
			audiences := strings.Split(audienceStr, ",")
			seen := make(map[string]bool)
			for _, a := range audiences {
				if a == "" {
					return nil, fmt.Errorf("line %d: empty audience in list", lineNum)
				}
				if seen[a] {
					return nil, fmt.Errorf("line %d: duplicate audience %q in marker", lineNum, a)
				}
				seen[a] = true
				if a != "orchestrator" && a != "worker" && a != "all" {
					return nil, fmt.Errorf("line %d: unknown audience %q (must be subset of orchestrator, worker, all)", lineNum, a)
				}
			}

			if currentSec != nil {
				currentSec.Content = currentBody.String()
				sections = append(sections, *currentSec)
				currentBody.Reset()
			}
			currentSec = &Section{Audiences: audiences}
		} else {
			if currentSec == nil {
				if strings.TrimSpace(line) != "" {
					return nil, fmt.Errorf("line %d: text before first section marker", lineNum)
				}
			} else {
				currentBody.WriteString(line)
				currentBody.WriteString("\n")
			}
		}
	}

	if currentSec != nil {
		currentSec.Content = currentBody.String()
		sections = append(sections, *currentSec)
	}

	if len(sections) == 0 {
		return nil, fmt.Errorf("line 1: source has no section markers")
	}

	return sections, nil
}

// Render produces the generated agent instruction files (CLAUDE.md, GEMINI.md, AGENTS.md)
// from parsed sections and the source hash.
func Render(sections []Section, srcHash string) map[string][]byte {
	if len(srcHash) > 12 {
		srcHash = srcHash[:12]
	}

	marker := fmt.Sprintf("<!-- GENERATED by lucind-ai rules generate from lucind-rules.md (sha256:%s); do not edit, change the source and regenerate -->\n\n", srcHash)

	targets := []struct {
		filename string
		title    string
		match    func(audiences []string) bool
	}{
		{
			filename: "CLAUDE.md",
			title:    "# Agent rules: orchestrator",
			match: func(audiences []string) bool {
				for _, a := range audiences {
					if a == "orchestrator" || a == "all" {
						return true
					}
				}
				return false
			},
		},
		{
			filename: "GEMINI.md",
			title:    "# Agent rules: worker",
			match: func(audiences []string) bool {
				for _, a := range audiences {
					if a == "worker" || a == "all" {
						return true
					}
				}
				return false
			},
		},
		{
			filename: "AGENTS.md",
			title:    "# Agent rules: implementers",
			match: func(audiences []string) bool {
				for _, a := range audiences {
					if a == "worker" || a == "all" {
						return true
					}
				}
				return false
			},
		},
	}

	result := make(map[string][]byte, len(targets))

	for _, t := range targets {
		var buf bytes.Buffer
		buf.WriteString(marker)
		buf.WriteString(t.title)
		buf.WriteString("\n\n")

		first := true
		for _, sec := range sections {
			if t.match(sec.Audiences) {
				body := strings.TrimSpace(sec.Content)
				if body != "" {
					if !first {
						buf.WriteString("\n\n")
					}
					buf.WriteString(body)
					first = false
				}
			}
		}
		buf.WriteString("\n")
		result[t.filename] = buf.Bytes()
	}

	return result
}

// DefaultSource returns the embedded default rules source file content.
func DefaultSource() []byte {
	return defaultRules
}

func validateRoot(root string) (string, error) {
	if root == "" {
		return "", fmt.Errorf("root directory cannot be empty")
	}
	fi, err := os.Stat(root)
	if err != nil {
		return "", fmt.Errorf("root directory %q: %w", root, err)
	}
	if !fi.IsDir() {
		return "", fmt.Errorf("root %q is not a directory", root)
	}
	realRoot, err := filepath.EvalSymlinks(root)
	if err != nil {
		return "", fmt.Errorf("eval symlinks for root %q: %w", root, err)
	}
	realRoot, err = filepath.Abs(realRoot)
	if err != nil {
		return "", fmt.Errorf("abs path for root %q: %w", root, err)
	}

	home, err := os.UserHomeDir()
	if err == nil && home != "" {
		realHome, err := filepath.EvalSymlinks(home)
		if err != nil {
			realHome = home
		}
		realHome, _ = filepath.Abs(realHome)

		forbiddenList := []string{
			filepath.Join(realHome, ".claude"),
			filepath.Join(realHome, ".gemini"),
			filepath.Join(home, ".claude"),
			filepath.Join(home, ".gemini"),
		}

		for _, fp := range forbiddenList {
			resolved := fp
			if r, err := filepath.EvalSymlinks(fp); err == nil {
				resolved, _ = filepath.Abs(r)
			}
			if isInsideOrEqual(realRoot, resolved) {
				return "", fmt.Errorf("refusing forbidden root %q: target is or is inside user configuration directory %q", root, fp)
			}
		}
	}

	return realRoot, nil
}

func isInsideOrEqual(path, target string) bool {
	rel, err := filepath.Rel(target, path)
	if err != nil {
		return false
	}
	// Only a real parent traversal means "outside"; a directory merely named "..foo" is inside.
	return rel == "." || (rel != ".." && !strings.HasPrefix(rel, ".."+string(filepath.Separator)) && !filepath.IsAbs(rel))
}

func atomicWrite(dest string, content []byte) error {
	dir := filepath.Dir(dest)
	base := filepath.Base(dest)
	tmpFile, err := os.CreateTemp(dir, "."+base+".tmp*")
	if err != nil {
		return fmt.Errorf("create temp file in %s: %w", dir, err)
	}
	tmpName := tmpFile.Name()
	cleanedUp := false
	defer func() {
		if !cleanedUp {
			_ = tmpFile.Close()
			_ = os.Remove(tmpName)
		}
	}()

	if err := tmpFile.Chmod(0644); err != nil {
		return fmt.Errorf("chmod temp file %s: %w", tmpName, err)
	}
	if _, err := tmpFile.Write(content); err != nil {
		return fmt.Errorf("write temp file %s: %w", tmpName, err)
	}
	if err := tmpFile.Close(); err != nil {
		return fmt.Errorf("close temp file %s: %w", tmpName, err)
	}

	if err := os.Rename(tmpName, dest); err != nil {
		return fmt.Errorf("rename %s to %s: %w", tmpName, dest, err)
	}
	cleanedUp = true
	return nil
}

// Generate reads <root>/lucind-rules.md and generates the agent instruction files.
func Generate(root string, opts Options) (Result, error) {
	realRoot, err := validateRoot(root)
	if err != nil {
		return Result{}, err
	}

	sourcePath := filepath.Join(realRoot, SourceName)
	src, err := os.ReadFile(sourcePath)
	if err != nil {
		if os.IsNotExist(err) {
			return Result{}, fmt.Errorf("source file %q does not exist; run 'lucind-ai rules init' to create it", sourcePath)
		}
		return Result{}, fmt.Errorf("read source file %q: %w", sourcePath, err)
	}

	sections, err := Parse(src)
	if err != nil {
		return Result{}, err
	}

	h := sha256.Sum256(src)
	srcHash := hex.EncodeToString(h[:])
	rendered := Render(sections, srcHash)

	targetNames := []string{"CLAUDE.md", "GEMINI.md", "AGENTS.md"}
	res := Result{
		Files: make(map[string]FileStatus),
	}

	for _, name := range targetNames {
		targetPath := filepath.Join(realRoot, name)
		newContent := rendered[name]

		lfi, err := os.Lstat(targetPath)
		if err == nil {
			if lfi.Mode()&os.ModeSymlink != 0 {
				res.Targets = append(res.Targets, TargetResult{File: name, Status: StatusSkippedHandWritten})
				res.Files[name] = StatusSkippedHandWritten
				continue
			}
			if lfi.IsDir() {
				return Result{}, fmt.Errorf("target %s is a directory", targetPath)
			}
			existing, err := os.ReadFile(targetPath)
			if err != nil {
				return Result{}, fmt.Errorf("read target %s: %w", targetPath, err)
			}
			if !bytes.HasPrefix(existing, []byte(GeneratedMarkerPrefix)) {
				res.Targets = append(res.Targets, TargetResult{File: name, Status: StatusSkippedHandWritten})
				res.Files[name] = StatusSkippedHandWritten
			} else if bytes.Equal(existing, newContent) {
				res.Targets = append(res.Targets, TargetResult{File: name, Status: StatusUnchanged})
				res.Files[name] = StatusUnchanged
			} else {
				if opts.Check {
					res.Targets = append(res.Targets, TargetResult{File: name, Status: StatusStale})
					res.Files[name] = StatusStale
				} else {
					if err := atomicWrite(targetPath, newContent); err != nil {
						return Result{}, err
					}
					res.Targets = append(res.Targets, TargetResult{File: name, Status: StatusWritten})
					res.Files[name] = StatusWritten
				}
			}
		} else if os.IsNotExist(err) {
			if opts.Check {
				res.Targets = append(res.Targets, TargetResult{File: name, Status: StatusMissing})
				res.Files[name] = StatusMissing
			} else {
				if err := atomicWrite(targetPath, newContent); err != nil {
					return Result{}, err
				}
				res.Targets = append(res.Targets, TargetResult{File: name, Status: StatusWritten})
				res.Files[name] = StatusWritten
			}
		} else {
			return Result{}, fmt.Errorf("stat target %s: %w", targetPath, err)
		}
	}

	return res, nil
}

// InitSource writes the default rules source to <root>/lucind-rules.md if it does not exist.
func InitSource(root string) (written bool, err error) {
	realRoot, err := validateRoot(root)
	if err != nil {
		return false, err
	}

	sourcePath := filepath.Join(realRoot, SourceName)
	_, err = os.Lstat(sourcePath)
	if err == nil {
		return false, nil // never overwrites
	}
	if !os.IsNotExist(err) {
		return false, fmt.Errorf("stat source file %s: %w", sourcePath, err)
	}

	if err := atomicWrite(sourcePath, DefaultSource()); err != nil {
		return false, err
	}
	return true, nil
}
