#!/usr/bin/env bash
set -uo pipefail

# Check latest commit body for forbidden AI attribution trailers
BODY=$(git show -s --format="%b" HEAD 2>/dev/null || true)
if echo "$BODY" | grep -qiE "co-authored-by|co-authored by|generated-by|generated by|ai-assisted"; then
  echo "⚠️  [lucind-ai] Forbidden AI attribution trailer detected in HEAD commit:" >&2
  echo "$BODY" | grep -iE "co-authored-by|co-authored by|generated-by|generated by|ai-assisted" >&2
  echo "⚠️  Please amend the commit before finishing the lane: git commit --amend" >&2
fi

exit 0
